### ISSUE TITLE
FR: pipeKSamplerAdvanced

### ISSUE THREAD

**Issue by DrJKL** [TinyTerra/ComfyUI_tinyterraNodes#10]
Mainly looking for `start_at_step`, `end_at_step`, `return_with_leftover_noise` to be able to refactor some existing workflows.

**Comment by TinyTerra** [comment]
Added pipeKSamplerAdvanced, let me know if it's not working as expected :)

**Comment by DrJKL** [comment]
Mostly :-D

2 notes:
- I forgot (didn't notice when posting) `add_noise` as one of the options in the built-in Advanced
- I also didn't see that the pipeKSampler and now the pipeKSamplerAdvanced have their own seed widgets by default instead of taking the seed from the pipe and exposing `optional_seed` as an input.

Thanks for the quick response!

**Comment by TinyTerra** [comment]
Updated it, hopefully that's better now

**Comment by DrJKL** [comment]
I think it's not picking up the seed from the pipe, maybe because it's `seed` there, but `noise_seed` in the Sampler?

**Comment by DrJKL** [comment]
I'll try to put 2 repros together

**Comment by DrJKL** [comment]
![workflow](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/448862/072796eb-7f7c-4555-b946-01b9b1675c0c)

**Comment by TinyTerra** [comment]
Ah of course. Sorry about that. Latest push should fix it:
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/51d8c153-dac9-4ee2-9d34-b5db840b868d)

**Comment by DrJKL** [comment]
Looks good, thanks!
