### ISSUE TITLE
Slow startup time when WAS nodes and REMBG installed

### ISSUE THREAD

**Issue by fofr** [TinyTerra/ComfyUI_tinyterraNodes#104]
With was-node-suite, rembg and tinyterraNodes, this custom node takes ~40-50s to start, because of something to do with rembg.

With `rembg`:
```
1.6 seconds: /src/ComfyUI/custom_nodes/ComfyUI_InstantID
1.8 seconds: /src/ComfyUI/custom_nodes/was-node-suite-comfyui
54.0 seconds: /src/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
```

Without `rembg`:
```
0.0 seconds: /src/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
1.4 seconds: /src/ComfyUI/custom_nodes/ComfyUI_InstantID
1.5 seconds: /src/ComfyUI/custom_nodes/was-node-suite-comfyui
```

I'm not sure what the exact cause is here. This is with rembg already installed, and the install option set to False.

**Comment by TinyTerra** [comment]
Thanks for pointing this out, and the example. I modified your change slightly to reraise the error with the extra information, instead of outputting from the node.

**Comment by fofr** [comment]
I can confirm this works 🙏
