### ISSUE TITLE
[bug] Conflict between tiny terra v2 and UE

### ISSUE THREAD

**Issue by novaexe** [TinyTerra/ComfyUI_tinyterraNodes#106]
![327977110-82390e8c-cc38-4179-b021-70b3ba8fbf55](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/69226867/ef5c6a19-bef2-40e7-8ed1-40cb0b9ac265)
![327977123-a8775349-10b9-4c54-9094-c6f6908cb893](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/69226867/a0e45426-02d2-487a-9931-762a7e9b61ee)
when tiny Terra is present anywhere on the workflow it disables UE's graphic's, the nodes are still connected, this is a visual bug

**Comment by TinyTerra** [comment]
Have submitted a PR to the UseEverywhere repo

**Comment by novaexe** [comment]
solved by https://github.com/chrisgoringe/cg-use-everywhere/pull/188
