### ISSUE TITLE
After update, 'imageOutput' nodes miss the folder destination input area

### ISSUE THREAD

**Issue by 925-Studio** [TinyTerra/ComfyUI_tinyterraNodes#110]
First, thanks for create and maintain this custom nodes, it's very helpful. But since I update to the latest version, it seems the folder destination input area is gone. Is this on purpose or something you miss? Anyway, thanks for your time. Really appreciate your work.

**Comment by TinyTerra** [comment]
I was doing some testing around that, and didn't mean to push the removal. Sorry about that.
I've re-added it in the latest push

**Comment by 925-Studio** [comment]
> I was doing some testing around that, and didn't mean to push the removal. Sorry about that. I've re-added it in the latest push

Thanks, now it's back.
