### ISSUE TITLE
pipeLoaderSDXL 'optional_controlnet_stack' input does not accept controlnet stack nodes

### ISSUE THREAD

**Issue by elphamale** [TinyTerra/ComfyUI_tinyterraNodes#111]
Pretty much subj.

Tried to rebuild the base of my workflows with tinyterranodes instead of Efficiency nodes. 
When it came to controlnet stacker, I couldn't connect any of controlnet stackers I have (efficiency, comfyroll) to optional_controlnet_stack input of pipeLoaderSDXL.

Expected behaviour would be accepting at least one of those stackers.

**Comment by TinyTerra** [comment]
They must have changed their input type at some point, in any case - thanks for pointing that out, I've pushed a fix and they should connect correctly now

**Comment by elphamale** [comment]
It does work correctly now. Thank you!
