### ISSUE TITLE
HiRes fix error

### ISSUE THREAD

**Issue by LoathingScreen** [TinyTerra/ComfyUI_tinyterraNodes#112]
Hey, first of all, thanks for your hard work. I'm getting this error when selecting HiRes fix in the KSampler SDXL node.
![Screenshot 2024-05-12 191503](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/31975841/0024901b-414f-4b75-9108-11cd3f420e7a)
![Screenshot 2024-05-12 191643](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/31975841/173aff46-a364-4e8f-acec-62b9b67d56bd)

**Comment by TinyTerra** [comment]
Sorry about that, This has been fixed in the latest push
