### ISSUE TITLE
positive_weight_interpretation and negative_weight_interpretation

### ISSUE THREAD

**Issue by cjps-br** [TinyTerra/ComfyUI_tinyterraNodes#113]
Are the positive_weight_interpretation and negative_weight_interpretation parameters working as they should? I did a test using each of the options, keeping all other parameters fixed (seed, prompts, etc.) and the images generated were exactly the same, regardless of which option was defined in the parameters.

**Comment by TinyTerra** [comment]
I believe they are, the effect is not as noticeable with basic prompts that don't have extensive weighting.
For example here is an xy with the prompt: '(cat:0.5), beach, (palm trees:1), volleyball, sunset'
that increases the weighting on palm trees.

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/04673d06-d743-4a53-8087-bf14d6e529ec)

Thats a relatively extreme example, but it highlights the effect better when there is weighting involved, even with minimal weight changes they perform fairly similarly

**Comment by cjps-br** [comment]
Ah, yes... I understand now. I tested using an unweighted prompt and the images were coming out the same. When I added weights, the images really changed. I didn't know about this difference. Thanks for this explanation!
