### ISSUE TITLE
after the update, xyplot image font very small

### ISSUE THREAD

**Issue by xiexiaobo135** [TinyTerra/ComfyUI_tinyterraNodes#123]
![ComfyUI_temp_mynbi_00001_](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/7458194/247b2a58-9ac6-4fdb-8ac0-4968da44dafd)

custom_nodes only has:
ComfyUI-Manager
comfyui-workspace-manager
ComfyUI_tinyterraNodes

[heelo.json](https://github.com/user-attachments/files/15560259/heelo.json)

**Comment by TinyTerra** [comment]
Apologies, this should be fixed in the latest push.

**Comment by xiexiaobo135** [comment]
Thank you for your timely repair
