### ISSUE TITLE
The optional_controlnet_stack never works. What controlnet stack would be supported by pipeLoaderSDXL?

### ISSUE THREAD

**Issue by mi-hang-lao-ban** [TinyTerra/ComfyUI_tinyterraNodes#124]
As can be seen in the screenshot, I've tried 3 different controlnet stack node but none of them are supported. Am I doing something wrong?

ttNloader.load_controlNet() takes 8 positional arguments but 9 were given
![cr](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/170563681/7f53a717-bcb1-4304-9055-101a58fad2d8)
![easy](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/170563681/42836059-5525-4bdb-b548-74c4cff5b5d4)

**Comment by TinyTerra** [comment]
Comfy roll should definitely supported so this is likely a bug.
I'll have a look into it shortly

**Comment by mi-hang-lao-ban** [comment]
您好，感谢您的来信，您的信件我已经收到。

**Comment by TinyTerra** [comment]
Please update tinyterra, and let me know if the issue still occurs

**Comment by mi-hang-lao-ban** [comment]
> Please update tinyterra, and let me know if the issue still occurs
Hi, Terra. Thank you for your timely reply. I've checked out the update, but another problem came out as shown in the screenshop.
I've tried all my sdxl openpose models. It's still not working.
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/170563681/d88a7313-c6ab-405f-a4a6-673cca0697d0)
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/170563681/eece0dd8-72ae-43da-9fe7-cba4ea6906ec)

**Comment by TinyTerra** [comment]
Sorry about that. The latest push should address this new issue.

**Comment by mi-hang-lao-ban** [comment]
Thank you, Terra. I've tested the update. The problem are well solved.
