### ISSUE TITLE
xyPlot_adv_not_support_GetNode_SetNode_Constant(bug)

### ISSUE THREAD

**Issue by xiexiaobo135** [TinyTerra/ComfyUI_tinyterraNodes#125]
When a variable node exists and is linked to KSamper, the parsing prompt box cannot be displayed in the text input box of the xyplotAdv node.

![Snipaste_2024-06-12_07-46-42](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/7458194/17d8a090-85c1-4e9c-824d-544f93adbc00)

[xyPlot_adv_not_support_GetNode_SetNode_Constant(bug).json](https://github.com/user-attachments/files/15795760/xyPlot_adv_not_support_GetNode_SetNode_Constant.bug.json)

**Comment by TinyTerra** [comment]
I'm assuming there is no hidden 'link' between the get set nodes like there is in UseAnywhere... so I'll have to explicitly add support for this. I'll see what i can do

**Comment by xiexiaobo135** [comment]
Look forward to your support for this feature. :)
