### ISSUE TITLE
Required input is missing: upscale_model_name

### ISSUE THREAD

**Issue by sassansa** [TinyTerra/ComfyUI_tinyterraNodes#126]
hi, i have a problem when clicked queue prompt, i got this error, hope to help me about this error
regards
![Screenshot 2024-06-13 163739](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/124548612/4b267162-42f0-4919-b6be-60dfbe2a688b)

**Comment by TinyTerra** [comment]
If you set upscale_method to one of the hiresfix options, and check that upscale_model_name shows up.
If not, please re-create the pipeKSampler node.
If it still doesnt work make sure comfy, and the node pack are both up to date.

Let me know if its still not working after that

**Comment by TinyTerra** [comment]
Nevermind, Looking at it a bit further it seems like an error that occurs when you have no Upscale Model in the upscale model folder.

I have pushed an update that should prevent this - you will need to either recreate the node after updating or manually set the upscale_model_name to none (by first setting upscale_method to one of the hiresfix options).
