### ISSUE TITLE
Glow for link in "straight style" mode.

### ISSUE THREAD

**Issue by pvp-by** [TinyTerra/ComfyUI_tinyterraNodes#13]
Thank you so much for your good work. I really like the realization of the **Link Style (ttN)**.
But in " **straight** style " mode all links tend to overlap and turn into 1 common link. and when you select a node the link highlighting goes only up to the common line 
example :
![Figure_7](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/10133995/c9ede7ce-2162-43b9-8ed6-ddadc40b09cb)

maybe in this "style mode **straight**" you can add more glow effect so that even a link that is at the bottom of the layers, still gives a hint where it goes.
example :
![Figure_8](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/10133995/a7ed01dc-4e7d-41cf-8b4e-338921089e70)

**Comment by TinyTerra** [comment]
I agree that the straight style isn't the clearest when it comes to overlapping lines, however the current implementation just adds a UI option within the comfy interface for an inbuilt function of LiteGraph... I'm not sure at the moment how litegraph handles line overlay priority, but I'll have a look into it

**Comment by TinyTerra** [comment]
If you right click on a link and change the ttn link style it will set the default for tinyterra - if that doesn't persist then I'll need to do some debugging. Let me know
