### ISSUE TITLE
Settings are inaccessible

### ISSUE THREAD

**Issue by brayevalerien** [TinyTerra/ComfyUI_tinyterraNodes#132]
I'm not sure if it is intended and I'm missing something or if it actually is an issue, but I cannot access the settings by right clicking:
![image](https://github.com/user-attachments/assets/53a3519a-a008-411e-8ba1-c4ca4717e968)
As you can see, the "⚙️ Settings (tinyterra)" option is grayed out.

But even if it was, I think putting the settings in the context menu is not ideal, they should instead be in the main settings menu of ComfyUI, just like the rest of the settings.

Just for context, I'm trying to disable the autocomplete when using an xyPlot advanced node, but I could not find that setting.

**Comment by TinyTerra** [comment]
Settings in the UI hasnt been implemented yet, I was planning on having it accessible from both the context menu and the main settings.
But time for this project has fallen short again.

Currently the settings are changeable in the config.ini file in the extension folder. You can disable the main autocomplete, but the xyplot specific dripdowns are not currently toggleable.

**Comment by brayevalerien** [comment]
I see, thank you for clarifying.

If they are not implemented yet, I think settings should not appear, neither in the UI nor in the readme, because it can be confusing.

**Comment by TinyTerra** [comment]
The settings in the readme are accessible via the config.ini file - they do work there it's just less user friendly than it would be in the ui
