### ISSUE TITLE
what's the purpose of "config_name" in pipeLoaderSDXL

### ISSUE THREAD

**Issue by ykhasia** [TinyTerra/ComfyUI_tinyterraNodes#133]
what's the purpose of "config_name" in pipeLoaderSDXL

**Comment by TinyTerra** [comment]
Some models come with a config file that modifies how the model is loaded.. in most cases it isn't needed unless you specifically know you need it/what it's doing.
In base comfy this method is deprecated now, but I have left it as an option in ttN.
