### ISSUE TITLE
what is the positive_l and positive_g?

### ISSUE THREAD

**Issue by ykhasia** [TinyTerra/ComfyUI_tinyterraNodes#134]
what is the purpose of positive_l and positive_g?

**Comment by TinyTerra** [comment]
They are seperate clip models within SDXL. In theory g is better at understanding natural language and the L for additional tokenized/comma seperated prompts.
In practise though it's better for them to be the same (which happens automatically if L is empty in ttN) .. in any case it's another level for users to experiment with to see how it changes generation
