### ISSUE TITLE
Node rightclick slot menu

### ISSUE THREAD

**Issue by Neuromaked** [TinyTerra/ComfyUI_tinyterraNodes#138]
Node rightclick slot menu not workes.
Mb this can be fixed somehow in these settings, but they are not active.
![Screenshot 2024-08-05 171824](https://github.com/user-attachments/assets/2b2d245c-19eb-434f-bed8-8cc594cc3a53)

**Comment by TinyTerra** [comment]
Does the slot menu not work in the old or new UI?

The settings button is greyed out because you settings in ttN hasn't been implemented yet

**Comment by Neuromaked** [comment]
Didn't work in the old UI. Today I updated to the new UI, and it works. Thanks
