### ISSUE TITLE
Flux/T5 compatibility for XY Plot?

### ISSUE THREAD

**Issue by EnragedAntelope** [TinyTerra/ComfyUI_tinyterraNodes#140]
Hi,
Thank you for making these nodes. I love the functionality of the XY plot especially.
Since Flux uses 2 text encoders (T5 and clip_l), it seems to hang up the XY plot. For reference I tried with the unified safetensors version of Flux: https://huggingface.co/marduk191/Flux.1_collection .

Can the XY nodes be updated to handle such a situation please? 

Error info:
![image](https://github.com/user-attachments/assets/d7b23951-0a75-41e0-99cf-b0771273ce81)

```
Loading 1 new model
!!! Exception during processing!!! 't5xxl'
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\tinyterraNodes.py", line 2316, in condition
    positive_embedding = loader.embedding_encode(positive, positive_token_normalization, positive_weight_interpretation, clip, title='ttN Conditioning Positive', my_unique_id=my_unique_id, prepend_text=prepend_positive)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\tinyterraNodes.py", line 249, in embedding_encode
    embedding, pooled = advanced_encode(clip, text, token_normalization, weight_interpretation, w_max=1.0, apply_to_pooled='enable')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\adv_encode.py", line 262, in advanced_encode
    return advanced_encode_from_tokens(tokenized['l'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\adv_encode.py", line 183, in advanced_encode_from_tokens
    weighted_emb, pooled_base = encode_func(weighted_tokens)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\adv_encode.py", line 265, in <lambda>
    lambda x: (clip.encode_from_tokens({'l': x}), None),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\sd.py", line 116, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\text_encoders\flux.py", line 55, in encode_token_weights
    token_weight_pairs_t5 = token_weight_pairs["t5xxl"]
                            ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 't5xxl'
```

**Comment by SouthbayJay** [comment]
Hey yeah that would be great if we can get them updated for Flux and also the new version of ComfyUI rolling out in a couple days on the 15th. I had issues with some of your nodes, PipeKsampler in the new version. I had to revery back to the old version in order to get the node to work..

**Comment by TinyTerra** [comment]
I am working on T5 support, it's mostly implemented but there are a few quirks I still need to iron out before updating. 

@SouthbayJay please make a seperate issue for the new UI problems with specific examples of errors

**Comment by SouthbayJay** [comment]
> I am working on T5 support, it's mostly implemented but there are a few quirks I still need to iron out before updating.
> 
> @SouthbayJay please make a seperate issue for the new UI problems with specific examples of errors

That's fantastic news! 

Sure no problem, I switch back to the legacy version of Comfy but I can switch back to the new version so I can give you all the details..

**Comment by TinyTerra** [comment]
I've pushed an update to support Flux.

Currently comfy++ and down_weight interpretation methods aren't supported.

Another thing to keep in mind - Flux seems to require a clip_skip of 0 or it will error out.

I've also implemented automatic SD3 empty latent creation, depending on the model

**Comment by TinyTerra** [comment]
> I had issues with some of your nodes, PipeKsampler in the new version. I had to revery back to the old version in order to get the node to work..

On this note, i hadn't actually tried the new UI yet, but you are right, there were 3 nodes that weren't being loaded correctly, which should also be fixed now

**Comment by EnragedAntelope** [comment]
You're awesome. Thank you!
