### ISSUE TITLE
missing nodes issue

### ISSUE THREAD

**Issue by ENIACZH** [TinyTerra/ComfyUI_tinyterraNodes#141]
I've cloned the ComfyUI_tinyterraNodes repository into the custom_nodes directory, but I'm still encountering a "missing nodes" issue when I run ComfyUI.

**Comment by ENIACZH** [comment]
![Weixin Screenshot_20240810120046](https://github.com/user-attachments/assets/89ce448b-e108-4428-9068-a7f9bc1eb66a)
![Weixin Screenshot_20240810115857](https://github.com/user-attachments/assets/8b1e76ad-1ab3-4c50-8206-904b895e44c8)

**Comment by TinyTerra** [comment]
Please try deleting the whole tinyterra folder and cloning it from GitHub.

If the error still happens:
Is that an old workflow? Are other tinyterra nodes showing up in the node menu?

**Comment by ENIACZH** [comment]
I've tried deleting the entire folder and cloning it again from GitHub, but the issue persists. I also attempted to download thea ZIP file and manually replace the folder, but that didn't work either.

In ComfyUI, all three tinyterra nodes are still showing up as red (missing).

**Comment by TinyTerra** [comment]
Which workflow are you using? It's possible if it's fairly old that those particular nodes are old versions that are no longer available. Are any of the ttN nodes present in the node menu?

**Comment by ENIACZH** [comment]
I resolved the issue by upgrading all core to the latest versions!!!!thanks!!!!
