### ISSUE TITLE
ttN pipeLoaderSDXL_v2 missing with new ComfyUI FrontEnd

### ISSUE THREAD

**Issue by lukehoggett** [TinyTerra/ComfyUI_tinyterraNodes#145]
The new ComfyUI Frontend is now the default and the ttN pipeLoaderSDXL_v2 is coming up as missing.

Specifically ComfyUI Front-end version: 1.2.23, but I have seen it I started previewing the new FE at 1.2.14

![image](https://github.com/user-attachments/assets/4a1e06e0-e8ab-4dac-ac92-c5504795a798)
I don't know if it's related to the browser console errors for ttN

![image](https://github.com/user-attachments/assets/a43b8058-d36b-4d87-b7d5-214be56fee6d)

**Comment by TinyTerra** [comment]
Please update ttN :)
This was fixed in https://github.com/TinyTerra/ComfyUI_tinyterraNodes/commit/51f32fbf74821c454ef16d6d1a5e66b772995e0b

**Comment by lukehoggett** [comment]
AH, thank you, yes it is indeed fixed, much appreciated. Not sure why it didn't work initially, I was all updated.
