### ISSUE TITLE
option 'pipeloader_v2' in section 'Versions' already exists

### ISSUE THREAD

**Issue by flybirdxx** [TinyTerra/ComfyUI_tinyterraNodes#147]
![image](https://github.com/user-attachments/assets/c2252815-a3cd-4002-af34-9a1a18424184)

**Comment by flybirdxx** [comment]
![image](https://github.com/user-attachments/assets/9fdfcfe2-6b5e-44f7-a5ae-776e05b05b98)
I found a duplicate pipeloader_v2 inside the config file.

**Comment by TinyTerra** [comment]
Try removing one of them and restarting comfy
