### ISSUE TITLE
When Using Queue Trigger Logic, only 3 prompts execute, when it should actually do 6 based on the .txt

### ISSUE THREAD

**Issue by boricuapab** [TinyTerra/ComfyUI_tinyterraNodes#155]
Hi I've made this workflow with a bit of queue trigger logic to run xy grids for 6 prompts from a .txt file, but only 3 prompts trigger.  Is there a limit to how many different xy grids get triggered in one go?

Here's an example .json

[fluxGGUFXYGridLoraTriggersOnly3Prompts.json](https://github.com/user-attachments/files/17447343/fluxGGUFXYGridLoraTriggersOnly3Prompts.json)

And here's the .txt file I'm using

[promptsFluxDevXYPlot.txt](https://github.com/user-attachments/files/17447351/promptsFluxDevXYPlot.txt)

**Comment by TinyTerra** [comment]
Im kind of surprised that works at all.. the way the XYPlot works is by re-executing the relevant graph nodes - so in theory it would go through the whole cycle for each plot..

If you want to create a plot for each separate prompt, I'd recommend just using the Z option in the advanced xyPlot node.
something like this would achieve what i assume is what you're trying to do:
![image](https://github.com/user-attachments/assets/0376c272-ec88-4b72-96cd-fbc9eaa50faa)

**Comment by boricuapab** [comment]
Thanks for the suggestion
