### ISSUE TITLE
Question about the hires upscale

### ISSUE THREAD

**Issue by TyleRxYan** [TinyTerra/ComfyUI_tinyterraNodes#156]
How is this thing work? the function seems not work like simple tiled resample, also not upscale by model, I've keep get multiple objects in final image if I bump the rescale percent above 50.

**Comment by TinyTerra** [comment]
It first does a model upscale and then does a latent rescale (usually downscale).

using say 4x_NMKD-superscale model on a 512x512 image, it will
1) 4x model upscale > 2048x2048
2) 50% latent scale > 1024x1024


that node (and the hiresfix upscale method within the ttN sampler nodes) performs a similar process to the nodes between the two samplers here:
![image](https://github.com/user-attachments/assets/7c1959e4-d593-45e0-adae-202a39f9a3eb)

**Comment by TyleRxYan** [comment]
> It first does a model upscale and then does an image rescale (usually downscale).
> 
> using say 4x_NMKD-superscale model on a 512x512 image, it will
> 
> 1. 4x model upscale > 2048x2048
> 2. 50% image scale > 1024x1024

the pipeKSamplerSDXL is not quite like ttN hiresfixScale, the sample process is final stage, sorry I wasn't make it clear at first. 
If the progress like what you said, I think the problem is SDXL node

**Comment by TinyTerra** [comment]
The same process happens inside the SDXL kSampler. 

Are you using the upscale within the ksampler?

in that case the upscale occurs first before the re-sampling (in the example image that would be the same as the second ksampler with the previous upscaling)

**Comment by TyleRxYan** [comment]
> The same process happens inside the SDXL kSampler.
> 
> Are you using the upscale within the ksampler?
> 
> in that case the upscale occurs first before the re-sampling (in the example image that would be the same as the second ksampler with the previous upscaling)

yeah, the upscale within the ksampler. 

![71237f5b-32b2-46f4-8567-4a0b4201649c](https://github.com/user-attachments/assets/de025cc8-9877-40e0-be75-c0373806cda7)

**Comment by TinyTerra** [comment]
Here you are upscaling an empty latent - which is why this issue is happening.

The upscale is meant to be used after the initial sampling

![hiresfix](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/raw/main/images/tinyterra_trueHRFix.png)


A side note - If you're not using a refiner i'd recommend just using the regular pipeKsampler

**Comment by TyleRxYan** [comment]
I see, thank you for the patience.
