### ISSUE TITLE
request - folder hierarchical view for embeddings add

### ISSUE THREAD

**Issue by EricRollei** [TinyTerra/ComfyUI_tinyterraNodes#17]
Your autocomplete embedding filenames in text widgets is brilliant!  But I have like 200 embeddings saved into different folders - pos, negative, characters, genre, environment, tools, etc   and it would be super helpful if your pop up could show the folder views.  A lot of embeddings have hard to remember names so it's easiest to find them via the folders.  So a feature request to show the folders...  thanks!

**Comment by TinyTerra** [comment]
Yeah true, good idea! I'll work on implementing it soon

**Comment by TinyTerra** [comment]
This has been added in b5768b4669e397316050b3bb21c3adc122a468ab :)
