### ISSUE TITLE
Massive performance hit caused by this repo's last commit (0bba92f0942a781f56374b31e8adc1ca10e36794).

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [TinyTerra/ComfyUI_tinyterraNodes#18]
For the past 12 hours I've been trying to work out what has been causing my 32Gb RAM to be exhausted and continual disk caching when creating a single SDXL image (RTX4090 was hardly being used). Yesterday this would take a few seconds and not cause and issue with resources, but after updating the nodes to hash 0bba92f0942a781f56374b31e8adc1ca10e36794 I've had continual problems. I finally tracked it to these nodes after rolling back to the previous commit. 

Initial load time is usually longer because it's loading the models, but latest commit shows 2nd time is even longer, perhaps a memory leak?

These are the gen time differences between them...

0bba92f0942a781f56374b31e8adc1ca10e36794
![Screenshot 2023-08-04 191617](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/14972c5b-fdaa-4b3a-b13b-55200f1db940)

160f66d9805aa53ada4659d234d8ef48acc93cc3
![Screenshot 2023-08-04 194724](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/3485bf17-a303-446c-a029-ff21df008fd2)

**Comment by viewscreenon** [comment]
Yeah, I'm also seeing a very long startup time on the sampler node, presumably starting with this last update. I'm just using 1.5 models, not SDXL.

**Comment by EricRollei** [comment]
I've also seen the issue.  It's also taking more RAM on successive gens and not releasing it even after workflow is cleared and browser window closed.  Have to close the console window and restart.

**Comment by TinyTerra** [comment]
Fairly sure this was being caused by deepcopy - which has been removed in 5665f6bc16ecc2f27f5da39eb42c6c7587fee225

**Comment by GalaxyTimeMachine** [comment]
Much better now, thank you!
