### ISSUE TITLE
Conflict issue with the LINK_RENDER_MODES setting feature

### ISSUE THREAD

**Issue by ltdrdata** [TinyTerra/ComfyUI_tinyterraNodes#19]
In the latest ComfyUI release, LINK_RENDER_MODES has been added as a default setting. However, when installing the TinyTerra extension, due to conflicts, the initial setting value of LINK_RENDER_MODES is not applied, resulting in the issue where it always defaults to "Straight". (Even though the combo is set to "Spline" in the settings, to properly apply Spline, you need to change it to another option and then switch back to "Spline" again.)

**Comment by TinyTerra** [comment]
This should be fixed in 0e64763326fbc7145fbb94d9469e443b742e9504 , Thanks :)
