### ISSUE TITLE
Are there any save_prefix tokens?

### ISSUE THREAD

**Issue by hortom** [TinyTerra/ComfyUI_tinyterraNodes#2]
Hi, thank you for your amazing nodes.
Is there a way to add `save_prefix` tokens (e.g. ComfyUUI's default `%date:yyyy-MM-dd-hh-mm-ss%` or Was Suite's `[time(%Y-%m-%d-%H-%M-%S)]`)?
I can't find a way to save the generation date and time in the filename directly from the pipeKSampler. Did I miss anything?

**Comment by TinyTerra** [comment]
There wasn't.. but the latest push should follow the default comfy format now. Let me know if its working

**Comment by hortom** [comment]
Yes, it works, thank you!

**Comment by TinyTerra** [comment]
Perfect :)
