### ISSUE TITLE
Image prefix parsing doesn't seem to work

### ISSUE THREAD

**Issue by tusharbhutt** [TinyTerra/ComfyUI_tinyterraNodes#22]
As per the title... I used the default workflow in ComfyUI and I get an error:

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/26264462/9d43c267-ca4a-485f-8a6d-8687adc623b1)

The flow I am using is below:

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/26264462/a6685bef-b1fa-4ab9-a232-3bd8c63434a5)

So I figure the prefix is to be

> 
ComfyUI-%images>samples>model>ckpt_name%

Am I doing something incorrect?  Thanks for any help you can offer

**Comment by TinyTerra** [comment]
That's the correct formatting, but it only works with tinyterra save nodes (save image in ksamp for example) - 

For this workflow you can replace the save image node with imageOutput from this pack and it should work then

**Comment by tusharbhutt** [comment]
Oh OK, thanks, good to know.
