### ISSUE TITLE
All Text Concats cutting off text

### ISSUE THREAD

**Issue by Chubbly** [TinyTerra/ComfyUI_tinyterraNodes#26]
It appears that the text concats are cutting off text when it is passed in. See simple workflow below

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/5073911/0ff12e85-9fb0-44ae-801c-7663df684a13)

**Comment by TinyTerra** [comment]
Merged - thanks :)
I've seen this pop up before - javascript being funky about how text is passed to it
