### ISSUE TITLE
Seed not passed to pipeKSampler from pipe?

### ISSUE THREAD

**Issue by tomvdp** [TinyTerra/ComfyUI_tinyterraNodes#29]
The seed set in a pipeLoader does not get loaded in a connected pipeKSampler. By default the seed of the Sampler is set to 0. Then that is the value that will be used, not the value from the pipe.

There is this in the code for ttN_TSC_pipeKSampler.sample(), but how does one set the seed in the pipeKSampler to None or undefined? A value of -1 yields an error.

`...
        if seed in (None, 'undefined'):
            seed = pipe["seed"]
        else:
            pipe["seed"] = seed
...
`

**Comment by TinyTerra** [comment]
To use the upstream seed value you need to convert the seed widget in the pipeksamp to an input (you don't need to connect the link after)

**Comment by tomvdp** [comment]
Thank you. Indeed, that was the solution. I missed that option.
