### ISSUE TITLE
Prompts not being loaded from pipeLoader 

### ISSUE THREAD

**Issue by viewscreenon** [TinyTerra/ComfyUI_tinyterraNodes#3]
I just updated ComfyUI and your extension to the newest versions. It looks like pipeLoader is not showing the prompt text it loads from files, and does not take input when I input new text. 

By the way, thank you for some of your other recent updates like the embedding list and collapsing unused parts of the node. I appreciate them.

**Comment by TinyTerra** [comment]
Glad to hear you find the new features useful!

I'm not 100% what the issue you're facing is.. if you could include some screenshots of what should be happening vs what is happening or a workflow so I can better troubleshoot and understand the issue that would be helpful

**Comment by viewscreenon** [comment]
Thanks for looking into it.

Basically, the prompt boxes in pipeLoader don't seem to be reading my input. For example, if I start a new workflow with pipeLoader connected to pipeKSampler, the rendered image will always look like the prompt was just the word "Positive" (which is what starts out in the box.)

If I load from an image I previously made with your nodes, the text boxes in pipeLoader will display "Positive" and "Negative" instead of the prompts I used. If I generate an image, it actually will use the prompts loaded from the image, even though the prompts are not shown in the UI. If I change the prompts in pipeLoader, it will generate images as if the prompt has not changed.

**Comment by TinyTerra** [comment]
Okay, sorry about this... I've narrowed it down to the dynamicWidgets code.. so if you set enable_dynamic_widgets to False in the tinyterra config.ini that should fix it in the meantime - until i've patched it properly.

**Comment by TinyTerra** [comment]
Just pushed a fix for this... let me know if it works as expected now

**Comment by viewscreenon** [comment]
I didn't have a chance to test it extensively, but
