### ISSUE TITLE
New SDXL nodes take forever

### ISSUE THREAD

**Issue by mattymatty** [TinyTerra/ComfyUI_tinyterraNodes#34]
I used your old nodes from a week ago and it took 15second to generate
now they take 160second to generate. even after the initial generation

**Comment by TinyTerra** [comment]
Do you mean the pipeSDXL nodes compared to the regular pipe node sdxl workflow?
And if so are they both slower now or only the pipeSDXL nodes?

**Comment by mattymatty** [comment]
ttN pipeLoaderSDXL and ttN pipeKSamplerSDXL. It seems as though it loads the models each time and doesn't keep the cache.

**Comment by TinyTerra** [comment]
Ah I see, this should be fixed in f2f443ff99bcf49870d9a4bd4caa84a063d49378

**Comment by mattymatty** [comment]
It's much faster now! Greatness!
