### ISSUE TITLE
Poor performance, high VRAM usage.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [TinyTerra/ComfyUI_tinyterraNodes#37]
The PipeLoaderSDXL and PipeKSamplerSDXL combination are now unusable for me. I have an RTX4090 and the 24GB VRAM is maxed out, and shared VRAM is being used., which makes creating anything impossible. I've switched to the built-in KSampler (Advanced) nodes and the VRAM usage doesn't go above 20GB.

**Comment by TinyTerra** [comment]
This is likely due to the pipeLoader attempting to keep both the base and refiner model loaded...
Do the models get reloaded each time using the built-in nodes?
Could you share both node setups and any relevant log messages.. and I'll try to sort it out

**Comment by GalaxyTimeMachine** [comment]
There aren't really any log messages, it continues to work, just at an extremely slow pace. I'll upload the workflows when I'm back at the PC.

**Comment by GalaxyTimeMachine** [comment]
This shows the VRAM usage for the 1st image generation after starting ComfyUI:
![Screenshot 2023-08-29 082157](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/bf977f58-f66b-491b-a45d-675767461d7b)
The problem really starts are about 4 or 5 images have been generated, and this image is after the 3rd gen. Note how the shared memory is already starting to be used, and idle VRAM usage is over 20GB:
![Screenshot 2023-08-29 082422](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/47713648-0d00-4754-b564-e3a64c0e32e0)
This was the workflow used:
![workflow](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/1a50764e-2b71-4107-b06a-83930c4c6c90)
Eventually it gets to the stage where nothing responds and I have to just close the ComfyUI server window to clear the memory:
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/768f489c-55f9-46e8-8b68-2a4c95408eca)

**Comment by GalaxyTimeMachine** [comment]
Using this workflow:
![workflow](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/74b6bf67-9050-45c3-80dc-e12ba7db7018)
This is how the VRAM usage looks on the 1st image generation, and shows the idle VRAM usage dropping to 14.9GB:
![Screenshot 2023-08-29 083831](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/6d36ff40-2da9-4496-80c4-d8a6af542e16)
I can keep creating more images, and it ramps up to 18.1GB of VRAM usage, but then drops back down to 14.9GB and never uses shared VRAM.

**Comment by GalaxyTimeMachine** [comment]
I did initially report the problem in ComfyUI, but eventually traced it to the ttN nodes. There was one time an error was reported (maybe it helps?), and it was logged in the report at https://github.com/comfyanonymous/ComfyUI/issues/1332#issuecomment-1694444943

**Comment by TinyTerra** [comment]
Is this still occurring after the latest push?

**Comment by GalaxyTimeMachine** [comment]
It is still using more than the available physical VRAM, and that is only creating a single SDXL image. I thought I could at least avoid it by not using the refiner now, but this is how that looks...
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52193044/14052461-d179-4c5e-b716-b6670a50b173)
