### ISSUE TITLE
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\User\ComfyUI\comfy\sd.py)

### ISSUE THREAD

**Issue by mattymatty** [TinyTerra/ComfyUI_tinyterraNodes#38]
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\User\ComfyUI\comfy\sd.py)

**Comment by mattymatty** [comment]
I think tinyterraNodes needs to be updated with
```
from comfy.model_patcher import ModelPatcher
from comfy.sd import sdxl_clip, VAE
```

**Comment by TinyTerra** [comment]
I've updated the imports in 18bf5df328a47ba38ab1043940ff11d4396e2bb4 - let me know if theres any issues

**Comment by mattymatty** [comment]
Resolved
