### ISSUE TITLE
TTn not Loading after update

### ISSUE THREAD

**Issue by Piscabo** [TinyTerra/ComfyUI_tinyterraNodes#43]
After the latest update:
Cannot import C:\AI_Files\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\AI_Files\ComfyUI\comfy\sd.py)

What is the fix?
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/123719842/f451fe1a-7bdd-49db-8124-a272fe44818e)

**Comment by TinyTerra** [comment]
You will need to update ComfyUI as this import change was made to patch a change made to the base program (use the update_comfui.bat script)
