### ISSUE TITLE
Any chance to improve import times?

### ISSUE THREAD

**Issue by onzu-cb** [TinyTerra/ComfyUI_tinyterraNodes#44]
First of all thank you for all the work and effort you put into this. Very much appreciated!

I'm using the nodes within a workflow that is hosted with AWS Sagemaker using auto scaling. When scaling up it's important to reduce the time to fire up a new instance to a minimum. There are some other custom nodes used with the ComfyUI workflow, all of them imported within 1 second.  Only the tinyterraNodes take 25 seconds to import and delaying the instance startup from ~5 seconds to ~30 seconds.

Is there any way to improve the import time?

A small note: In my ComfyUI setup I'm using the extra_model_paths.yaml to link additional folders containing model files/artifacts. Could this have an impact on the import time?

Thank you!

**Comment by TinyTerra** [comment]
Interesting.. it's usually only 1 second for me, so it's very possible that it is the extra model paths.. or something else strange happening.

I am away from my PC for the next few days unfortunately, so I won't be able to troubleshoot or adjust anything until then.

In the meantime, if you try running comfy without the extra paths yaml does the import time improve?
