### ISSUE TITLE
textDebug not showing text inside the node

### ISSUE THREAD

**Issue by alessandroperilli** [TinyTerra/ComfyUI_tinyterraNodes#46]
The textDebug node is very useful, thank you. I'm using it to verify that my very simple prompt builder is working as expected:

<img width="865" alt="Screenshot 2023-09-03 at 08 50 04" src="https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/9775949/546c16a5-f306-4f92-ab3f-a94c13ef3627">

Before your last commit, this setup would show the text concat both inside the node and in the terminal. After the commit, the concat only appears in the terminal. The node remains always empty.

Side note: the terminal print only appears when I modify the prompt, rather than at each generation. It would be nice if it could print the text at each generation.

Thank you

**Comment by WinstonWoof** [comment]
I'm seeing the same issue however only post a Core ComfyUI update

https://github.com/comfyanonymous/ComfyUI/issues/1397

**Comment by alessandroperilli** [comment]
Unrelated: @WinstonWoof your workflows are really cool. What node are you using for ChatGPT integration? Does it work well? As this is unrelated to the issue, let me know where I can contact you to continue this conversation. Thx

**Comment by WinstonWoof** [comment]
@alessandroperilli 

The answer to the question  re CHatGPT nodes is Omar92's QOL

https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92

There's a demo workflow in mine

https://civitai.com/user/Winston_Woof/models

**Comment by TinyTerra** [comment]
This should be fixed in 0d76921beca2d09ac8c0e29382f806aa4c7cd560 :)

**Comment by alessandroperilli** [comment]
It's great to see the new Execute option, but I'm afraid the bug is still there, @TinyTerra:

<img width="716" alt="Screenshot 2023-09-18 at 10 12 39" src="https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/9775949/6404e499-cbc2-4bed-a373-02ce87ac1b23">

Given that you are looking into this, I'll sneak in a feat request, if you don't mind: if you could add a text to append, it would be great. 

Desired behaviour:

- Inside the node: 2 fields, one for the append text (to be manually filled by the user) and one with the received input at workflow run time (not modifiable by the user, like now)

- In the terminal: print of the append string, if any, followed by the received input at workflow run time. If there's no append string, the node uses the default "STRING". 

Happy to open a dedicated issue for this feat request, if it helps.

**Comment by TinyTerra** [comment]
Apologies... the preview text should be fixed in f1d942d038d3b91def93b2fae893d6b88dceb100.
I've also added console_title that overrides the default 'input' console prefix.

And fixed the default behaviour (empty console_title) to use the label instead of the name of the output slot if it has been changed. _(If you rename the output slot of the inputting node it should now use the users label instead of the default value)_

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/3a578e4e-0aea-45e3-a7b8-a2453d83f6c2)

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/115619949/dc7f0b05-e7c6-455e-9712-d747352a0664)

**Comment by alessandroperilli** [comment]
Fixed and improved massively. Thank you!

**Comment by alessandroperilli** [comment]
I have to reopen this, sorry: 

The execute Always option does not work consistently work. 

I have one textDebug node that prints to console every time:

<img width="561" alt="Screenshot 2023-09-18 at 11 17 25" src="https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/9775949/d2461990-78ae-4e3e-a61d-2e422c8b94c4">

and one that refuses to:

<img width="482" alt="Screenshot 2023-09-18 at 11 15 38" src="https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/9775949/d4790bfa-e69c-4b88-b27e-7b071782f636">

I cannot tell what causes the difference in behaviour between the two.

**Comment by WinstonWoof** [comment]
apologies for the delay, Been having a nice city break in Prague :)

Yup all working as expected again, cheers
