### ISSUE TITLE
Feature Request: Add a "none" option for the refiner in pipeLoaderSDXL node.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [TinyTerra/ComfyUI_tinyterraNodes#52]
Not all models play well with a refiner, so being able to disable the refiner stages in some way, and not have to waste time and space loading a refiner model would be good.

**Comment by GalaxyTimeMachine** [comment]
The pipeKSamplerSDXL node would also need to be able to accept 0 for the refiner steps.

**Comment by TinyTerra** [comment]
In cases where you only need a single model you should be able to use the regular pipeLoader and pipeKSampler. Let me know if it's not working as expected

**Comment by GalaxyTimeMachine** [comment]
I just didn't want to have to create another workflow, just to avoid loading a model. Can't it work the same way as the Lora options, where "none" can be selected?

**Comment by TinyTerra** [comment]
Added this functionality in bdaf6f23d94ec78da98ce0f7101b2f81eb0fa608 - haven't had a chance to extensively test it though so please let me know if you come across any issues

**Comment by GalaxyTimeMachine** [comment]
Thanks! It does work, but I don't think it unloads the refiner if it was used before and then "none" is selected. The VRAM usage seems to be just as high without the refiner, but I don't know for sure if that's because it isn't unloading it.
