### ISSUE TITLE
issue: DETAILER_PIPE compatibility 

### ISSUE THREAD

**Issue by ltdrdata** [TinyTerra/ComfyUI_tinyterraNodes#53]
https://github.com/TinyTerra/ComfyUI_tinyterraNodes/blob/a1bbce6334607fb195abbf7a7ea88a3a4b0fc5c7/tinyterraNodes.py#L2079

In the latest `Impact Pack`, 4 new items have been added to `DETAILER_PIPE`.

```
refiner_model, refiner_clip, refiner_positive, refiner_negative
```

**Comment by TinyTerra** [comment]
Thanks data,
Should be compatible again in dc38e5a8d776b96bbd204c93933b471a8c0a56c6
