### ISSUE TITLE
More than 3 lora

### ISSUE THREAD

**Issue by SoulxSlayer** [TinyTerra/ComfyUI_tinyterraNodes#54]
How can I use more than 3 loras? Tried a lot but nothing worked. Is there something I'm missing?

**Comment by TinyTerra** [comment]
There should be a lora_stack input in the pipeLoader, that you can add Lora's with.. I haven't pushed the next update with the pipelorastack node just yet, but it should be compatible with efficiency nodes Lora stack and others potentially as well.

The new node is ready though, so I will push that update tonight.

**Comment by SoulxSlayer** [comment]
I always resort to using Efficiency Nodes because of it having the loraStacker. Having it in TTN would be insanely good! TYSM! Amazing dev!

**Comment by TinyTerra** [comment]
Pushed pipeLoraStack in cf76dbd078ba0b272885bd7542b5388f7eb2ffe8

just fyi, for the lora's to have an effect on the conditioning as well you will need to use the pipeLoaders lora_stack input

Using the pipe line will load the loras on top of the existing pipe model/clip

Shout out if its not working as expected :)

**Comment by SoulxSlayer** [comment]
Working amazing! Thank you so much!
