### ISSUE TITLE
when use lanczos in ttn pipeKsampler, it show error result

### ISSUE THREAD

**Issue by xueqing0622** [TinyTerra/ComfyUI_tinyterraNodes#55]
I like to use the lanczos algorithm, because it smoothes out the zoomed pixels without smearing.
but when use lanczos in ttn pipeKsampler, it show error result, 
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/114840118/116635b7-5976-4878-bd71-624bc6fa444f)

And how about to add  lanczos to upsacle model in hiresFixScale
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/114840118/9ec05f78-fed6-4f67-aa8c-e39f849be31d)

just like SDwebui, I just need lanczos only, other model zoomed pixels will smearing
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/114840118/8802a1a7-5de0-4739-a038-eebd640ed990)
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/114840118/1b4e6c0b-f9fa-4845-aaf8-3e37cd3dd767)

**Comment by xueqing0622** [comment]
there are no error message, just use lanczos method up total mess,
and other upscale method also no good in ttn pipeKsampler
[ttn-sample-withUpsacle.json](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/files/12864530/ttn-sample-withUpsacle.json)

**Comment by xueqing0622** [comment]
I find some lanczos upscale nodes here, but lantent upscale still not good effect, use image to upscale and vaeEncoder better than lantent upscale.
https://githubfast.com/Extraltodeus/CustomComfyUINodes/blob/main/LatentByRatio_not_mine.py

**Comment by mijuku233** [comment]
`pipeKSampler`放大的是`latent`而非`图片`，它与一般的高清修复方法截然不同，使用`hiresfixScale`才能获得你想要的结果。
我认为`pipeKSampler`里的`upscal`是多余的，它不好用，有`hiresfixScale`就够了

**Comment by xueqing0622** [comment]
Of course, I look forward to your updates, and I'm going to be very critical.  

haha, just a joke! Plz update for new pipeKSampler. maybe can add a image input, to upscale then vaeEncode to latent in the pipeKSampler, I found a lot of  upscale for latent give us bad result.

**Comment by xueqing0622** [comment]
> `pipeKSampler` enlarges `latent` instead of `image`. It is completely different from the general high-definition repair method. Use `hiresfixScale` to get the results you want. I think we can add a `upscale by model` function to `pipeKSampler` to optimize the experience

Please go to the example I posted above, we are just exploring if it can be integrated together, not if you say it can only be this and that!

**Comment by TinyTerra** [comment]
The upscale methods within pipeksampler use the default comfy upscale methods.

As mijuku said, using hiresfix is the preferred method for a "true" hires upscale..

I'll consider adding model upscale into the ksampler, but it is already starting to get a little crowded.. we'll see

**Comment by TinyTerra** [comment]
Model upscale has been added to pipeKSampler_v2 in cfaecd01e7f3547b38c7e44f417655471a6b181a
