### ISSUE TITLE
PipeLoader reloading model unnecessarily?

### ISSUE THREAD

**Issue by viewscreenon** [TinyTerra/ComfyUI_tinyterraNodes#58]
I don't know when this started happening, but pipeLoader seems to be unnecessarily re-loading models when any of its parameters change. In a simple setup like this:
![Screenshot 2023-10-16 103939](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/130644820/29d9bfc1-5af6-447b-bb00-20f7818d1535)
If I generate an image then change a parameter in pipeLoader (such as changing the prompt or changing empty latent size), then I generate again, it has to re-load the model. It shouldn't have to re-load when only changing something like the prompt, right? 

I'm not sure when this started happening. I just came back and updated Comfy and its extensions after 2 months away.

**Comment by TinyTerra** [comment]
Yeah it should keep the model cached. I'm not currently able replicate this... There is a log message from base Comfy saying 'Loading 1 new model' - but it doesn't actually reload the model.

Would you mind sharing the console log?

**Comment by viewscreenon** [comment]
Here's the console after a model should already be loaded, I change the prompt in pipeLoader, and generate another image:
```
got prompt
model_type EPS
adm 0
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
Requested to load SD1ClipModel
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
You shouldn't move a model when it is dispatched on multiple devices.
loading in lowvram mode 1702.5432691574097
```
I am in lowvram mode on my laptop with only 4GB vram, using SD 1.5 models. 
I don't know if this is related, but I found that if I left config_name in pipeLoader as "Default" I got a CUDA out of memory error. So I set it to "v1-inference".
