### ISSUE TITLE
Error occurred when executing ttN pipeLoader:

### ISSUE THREAD

**Issue by zhourunfaLi** [TinyTerra/ComfyUI_tinyterraNodes#60]
Error occurred when executing ttN pipeLoader:
VAE.__init__() got an unexpected keyword argument 'ckpt_path'

Who can help me solve this problem？

**Comment by Piscabo** [comment]
Same Error from today:
Error occurred when executing ttN pipeLoader:

VAE.__init__() got an unexpected keyword argument 'ckpt_path'

File "A:\AI_Files\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "A:\AI_Files\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "A:\AI_Files\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 1159, in adv_pipeloader
vae = ttNcache.load_vae(vae_name)
File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 306, in load_vae
loaded_vae = comfy.sd.VAE(ckpt_path=vae_path)

**Comment by TinyTerra** [comment]
The latest comfy update changed the default car load method, I'll push an update to fix this shortly

**Comment by Piscabo** [comment]
> The latest comfy update changed the default vae load method, I'll push an update to fix this shortly

I realized if I use the baked VAE option, that error does not occur... if that can help you?

**Comment by TinyTerra** [comment]
da8116a90a3455304bd3c238c73f45fd963cd2eb should be compatible with the latest comfy commits

**Comment by zhourunfaLi** [comment]
@TinyTerra look forward

**Comment by TinyTerra** [comment]
This should be fixed in da8116a90a3455304bd3c238c73f45fd963cd2eb, have you updated the node pack?

**Comment by xueqing0622** [comment]
fixed now, thx!
