### ISSUE TITLE
XY plot for SDXL KSampler?

### ISSUE THREAD

**Issue by tiko13** [TinyTerra/ComfyUI_tinyterraNodes#62]
Hello, I noticed that there is commented out code for XYPlot in SDXL KSampler, but when i un-comment it, the XYPlot does not work (thats probably why its commented in the first place :D )
Please is there a way to make it work with SD XL? Thank you

**Comment by TinyTerra** [comment]
Correct hahah

I feel like the sdxl nodes need an overhaul in general, but it isn't super high on my list.. xyplot is a bit complex, but I'll see

**Comment by bridgesense** [comment]
Most of the newer checkpoints don't need a refiner anyway. I've been using the xyPlot tool with sdxl checkpoints on pipeKSampler just fine.

In fact, one thing I can do that I couldn't do on efficiency nodes was run an xyplot with checkpoints. My system would always crash when the checkpoint changed. I really like this xyplot tool. It's much simpler than having to build the same script with a bunch of nodes.

**Comment by TinyTerra** [comment]
I'm thinking of adding an advanced xyPlot node with multi-variable axis control... that should be a lot more dynamic and customizable hopefully...

This might be further down the line though, still need to figure out the finer details of how it will work, and how to make it a easy/friendly to use as possible

**Comment by rjgoif** [comment]
Would love to have a more flexible XY plot functionality. I hope you circle back to it sometime.

**Comment by TinyTerra** [comment]
It is still on the list, I have lost a bit of motivation and haven't had a whole lot of time for working on updating the node pack in general though.. so no promises on it being soon

**Comment by TinyTerra** [comment]
[V2](cfaecd01e7f3547b38c7e44f417655471a6b181a) has added advanced xyPlot for pipeLoader_v2 and pipeLoaderSDXL_v2.
There is some more detail about how it works in the readme.
The old xyplot has now been deprecated
