### ISSUE TITLE
postive v positive XY plot not working

### ISSUE THREAD

**Issue by DrGunnarMallon** [TinyTerra/ComfyUI_tinyterraNodes#63]
Hi,

First of all, many thanks for an amazing selection of custom nodes! I seem to be having an issue with the xy plot though. When I set both axes to 'positive', the sampler does not seem to take these into account, but only ever chooses one axis and repeats the same images for the second axis. Am I missing something? I've attached my workflow - any pointers would be greatly appreciated :)

![workflow (1)](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/66589937/5c8bd336-5601-4a90-8c3f-99b7d49ea1e9)

**Comment by TinyTerra** [comment]
Currently it only accepts one positive input.
And it overwrites the original positive prompt as well.

Perhaps I can add an append positive option as well, that would potentially work how you're expecting?

**Comment by DrGunnarMallon** [comment]
Hey, thanks for the reply - that makes a lot of sense now. I only recently switched over from A1111 and thought I was doing something wrong.

Adding an "append" function wouldn't really solve what I'm trying to do. I'm looking to have something like the type of medium ("photo", "painting", "anime") on the x-axis and artistic style ("impressionist", "cubist", "bauhaus") on the y-axis for a prompt of "impressionism photo of a cow in a field" to produce a 3x3 matrix of the 9 combinations. Hope that makes sense :)

**Comment by GrigJr** [comment]
A "Prompt Search/Replace" on both axis at the same time would be GREAT for ttn! The kind doctor is describing how it works in a1111: the first term is searched in the prompt, then successively replaced with the following ones

**Comment by TinyTerra** [comment]
V2 advanced xyplot now has more comprehensive plotting capabilities, including S&R for strings as per adf2aca27874f1910f8c9e71dba69184c9646807

there is more documentation in the readme as to how the new xyplot works, including the S&R format
