### ISSUE TITLE
Image dimensions to pipe?

### ISSUE THREAD

**Issue by GrigJr** [TinyTerra/ComfyUI_tinyterraNodes#67]
Most workflows today need the image dimensions somewhere down the line, it would be nice to get them from the pipe, so we don't have to do this - https://i.imgur.com/4Q9pnZr.png - just to be able to get the image wight and height in other places in the workflow.

**Comment by TinyTerra** [comment]
Technically the Information is already in pipe it's just not accessible. I'll add a width/length output in the next update, along with the option to choose from preset aspect ratios

**Comment by GrigJr** [comment]
Cheers, you're amazing!

**Comment by TinyTerra** [comment]
[V2](cfaecd01e7f3547b38c7e44f417655471a6b181a) has added width/height outputs to the pipeLoader and pipeLoader_SDXL
