### ISSUE TITLE
VAE wrong

### ISSUE THREAD

**Issue by cardenluo** [TinyTerra/ComfyUI_tinyterraNodes#68]
Error occurred when executing ttN pipeLoader:

VAE.__init__() got an unexpected keyword argument 'ckpt_path'

File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 1159, in adv_pipeloader
vae = ttNcache.load_vae(vae_name)
File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 306, in load_vae
loaded_vae = comfy.sd.VAE(ckpt_path=vae_path)

**Comment by cardenluo** [comment]
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/133877069/49b0469b-2abd-45a2-973f-31c46c51a6c4)

**Comment by imner0** [comment]
i have same problem but 

**please reply ASAP**

```
Error occurred when executing ttN pipeLoader:

__init__() got an unexpected keyword argument 'sd'

File "/home/studio-lab-user/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/studio-lab-user/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/studio-lab-user/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/tinyterraNodes.py", line 1160, in adv_pipeloader
vae = ttNcache.load_vae(vae_name)
File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/tinyterraNodes.py", line 307, in load_vae
loaded_vae = comfy.sd.VAE(sd=sd)

```

**Comment by TinyTerra** [comment]
> "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 306, in load_vae loaded_vae = comfy.sd.VAE(ckpt_path=vae_path)

I believe this issue was fixed 2 weeks ago, have you updated to the latest version of the node pack?


> i have same problem but
> 
> **please reply ASAP**
> File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/tinyterraNodes.py", line 307, in load_vae
> loaded_vae = comfy.sd.VAE(sd=sd)
> ```

this one looks like outdated comfyUI - please try updating to the latest release and let me know if this still happens

**Comment by cardenluo** [comment]
sorry ,I tried to upgrade comfyui, but there were too many bugs that prevented it from launching properly, so I've delayed to give up on upgrading.  I will try to upgrade it again after some time has passed and confirm if the bugs have been fixed.Thank you for your concern.

**Comment by Xiahussheng** [comment]
> > "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 306, in load_vae loaded_vae = comfy.sd.VAE(ckpt_path=vae_path)
> 
> I believe this issue was fixed 2 weeks ago, have you updated to the latest version of the node pack?
> 
> > i have same problem but
> > **please reply ASAP**
> > File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/tinyterraNodes.py", line 307, in load_vae
> > loaded_vae = comfy.sd.VAE(sd=sd)
> 
> this one looks like outdated comfyUI - please try updating to the latest release and let me know if this still happens

I've upgraded comfyUI and still have the same problem

![Uploading Snipaste_2023-11-04_22-26-55.png…]()

**Comment by Xiahussheng** [comment]
> > "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 306, in load_vae loaded_vae = comfy.sd.VAE(ckpt_path=vae_path)
> 
> I believe this issue was fixed 2 weeks ago, have you updated to the latest version of the node pack?
> 
> > i have same problem but
> > **please reply ASAP**
> > File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/tinyterraNodes.py", line 307, in load_vae
> > loaded_vae = comfy.sd.VAE(sd=sd)
> 
> this one looks like outdated comfyUI - please try updating to the latest release and let me know if this still happens

I've upgraded comfyUI and still have the same problem

<img width="625" alt="Snipaste_2023-11-04_22-26-55" src="https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/109142804/8ae7d6c1-3cd8-47d0-a521-d37a4bd12c37">

**Comment by cardenluo** [comment]
I upgraded comfyui, VAE can be used normally, thank you
