### ISSUE TITLE
list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by imner0** [TinyTerra/ComfyUI_tinyterraNodes#69]
seriously there are so many problem with this workflow, i can't even use this workflow for single time

> Error occurred when executing ttN pipeLoader:
> 
> list indices must be integers or slices, not str
> 
> File "/home/studio-lab-user/ComfyUI/execution.py", line 152, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "/home/studio-lab-user/ComfyUI/execution.py", line 82, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "/home/studio-lab-user/ComfyUI/execution.py", line 75, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/tinyterraNodes.py", line 1172, in adv_pipeloader
> positive_embeddings_final, positive_pooled = advanced_encode(clipped, positive, positive_token_normalization, positive_weight_interpretation, w_max=1.0, apply_to_pooled='enable')
> File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/adv_encode.py", line 262, in advanced_encode
> return advanced_encode_from_tokens(tokenized['l'],

**Comment by TinyTerra** [comment]
this is from a patch for a recent comfyUI update - the latest version of ttN is no longer backwards compatible with earlier versions of comfy
