### ISSUE TITLE
Lora loading in nodes not working

### ISSUE THREAD

**Issue by viewscreenon** [TinyTerra/ComfyUI_tinyterraNodes#7]
Attempting to load a lora in pipeLoader or pipeKSampler fails with the error: "'str' object has no attribute 'keys'". Possibly caused by Comfy's update to LoraLoader a couple of days ago? Of course I can still use loras with the separate lora loader node.

**Comment by TinyTerra** [comment]
I've fixed this for an upcoming update that i plan on pushing in a day or two - but yes it's because of comfy's update

**Comment by Jongulo** [comment]
getting this error as well, thanks in advance for the fix.

**Comment by viewscreenon** [comment]
Just trying out the new version and it seems to work well. Thanks!
