### ISSUE TITLE
Saving to folder

### ISSUE THREAD

**Issue by drago87** [TinyTerra/ComfyUI_tinyterraNodes#70]
When using the pipeKSampler/hiresfixScale and pipeKSampler nodes (only tried it on these nodes)
When i try to save to a foler with the node using `TinyTerra\ComfyUI1` or `TinyTerra/ComfyUI1` it saves the file to the output folder with the name `TinyTerra-ComfyUI1_00001` insted of putting it in the folder `TinyTerra` and the file name `ComfyUI1_00001`

I am using only the pipeLoader and pipeKSampler for the smallest test

**Comment by TinyTerra** [comment]
I'll fix this is the next update. Not too sure when that will be yet, hopefully within the week
