### ISSUE TITLE
Lora name in XY Plot doesn't handle spaces correctly

### ISSUE THREAD

**Issue by Dagbafrosty** [TinyTerra/ComfyUI_tinyterraNodes#76]
It seems like the autocomplete functionality doesn't like loras with spaces in their name. Selecting the autocomplete or making a typo after typing a space (such that there are no suggestions remaining) causes that entry to get removed. A lora with a space can be forced accepted by converting x value to input and passing the full name in a primitive.

One more thing is the model&clip shouldn't be capped at 4, there are some loras designed to use weights upto 7-9.

**Comment by TinyTerra** [comment]
Yup, working on improving xyplot for the next update. Not too sure when that will be though

**Comment by TinyTerra** [comment]
[V2](cfaecd01e7f3547b38c7e44f417655471a6b181a) has added advanced xyPlot for pipeLoader_v2 and pipeLoaderSDXL_v2.
There is some more detail about how it works in the readme.
The old xyplot has now been deprecated
