### ISSUE TITLE
variation_ seeds cannot be re-run after changing the weights.

### ISSUE THREAD

**Issue by cardenluo** [TinyTerra/ComfyUI_tinyterraNodes#78]
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/133877069/806f2e88-38f8-45a7-aee3-ecaf14d0d744)

**Comment by TinyTerra** [comment]
The ttN pipe KSampler advanced doesn't have a variation seed, so this node must be from a different pack?

**Comment by cardenluo** [comment]
Thank you for your reminder. It turns out that it is because "cg noise" will bring 2 new nodes in the Pipe directory.

**Comment by mijuku233** [comment]
Why does your node have the `variation_ seeds` widget?

**Comment by cardenluo** [comment]
it is "cg noise"

> Why does your node have the `variation_ seeds` widget?
