### ISSUE TITLE
hiresfixScale new input?

### ISSUE THREAD

**Issue by Takeover713** [TinyTerra/ComfyUI_tinyterraNodes#79]
Hello, today i updated my comfyui and all my custom nodes. Now the hiresfixscale node has a new "Info" input.  Im not sure what to connect there. The node wont work unless i hook something up to it. thank you in advance for any help.

![Screenshot 2023-11-30 173939](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/44397569/2088570c-3543-4613-a1d5-2f6ccb090377)

**Comment by TinyTerra** [comment]
Please reload the node and see if that fixes it (either by using the right-click context ttN reload Node, or by removing it and reading it manually), the info input shouldn't be there anymore

**Comment by Takeover713** [comment]
Hello, thank you for the reply. I tried what you said. Reloaded it and tried to add it back manually but i still get the info input. Tried to uninstall and reinstall the custom node but no luck on getting rid of that info input.  
im on this version of comfy. ComfyUI Revision: 1759 [c97be4db] | Released on '2023-11-30'

**Comment by TinyTerra** [comment]
Apologies, the input was still there, I just missed it earlier.

I've pushed a hotfix, if you update the node pack, and then reload the node again, hopefully that fixes it.

Let me know :)

**Comment by Takeover713** [comment]
no worries thank you for the work you put into this great custom node. i see that the info input is no longer there after update. now im getting this error though.

Error occurred when executing ttN hiresfixScale:

ttN_modelScale.upscale() missing 1 required positional argument: 'info'

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

**Comment by TinyTerra** [comment]
Of course... this is why you don't hotfix on the go :p

Should be fixed properly in the latest push. Again let me know if not

Glad you're finding the pack useful! :)

**Comment by Takeover713** [comment]
seems to be working again. thank you i greatly appreciate your help. Thank you for the amazing custom node :D
