### ISSUE TITLE
Error occurred when executing ttN pipeKSampler: 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by 2ouo** [TinyTerra/ComfyUI_tinyterraNodes#86]
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/127192794/6bd3e9b4-e866-40a2-a6aa-6a013aa89359)

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/127192794/99be1a78-14f6-49fe-8592-15aa5906f581)

Where is  'FreeTypeFont' object and attribute 'getsize'? What should I do?

**Comment by 2ouo** [comment]
All the google results lead to problem about Pillow version but Pillow has been degraded before.
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/127192794/0ab71901-03be-4d4b-a9b9-b326ad71f343)
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/127192794/6f95f58e-da94-4d79-86b1-8bd296013e1e)

**Comment by TinyTerra** [comment]
Apologies for the delay,
This should be handled correctly in (a4ff7781f5c687c267d40f4dad7d0cf187cc6033)

**Comment by 2ouo** [comment]
「你好，她已经收到来信。」（假期自动回复）Dear Sir or Madam, Woofleod has received your letter. (Auto-reply during vacation)
