### ISSUE TITLE
Where is 'denoise' in SDXL nodes? 

### ISSUE THREAD

**Issue by ykhasia** [TinyTerra/ComfyUI_tinyterraNodes#88]
Seems pipeKSamplerSDXL doesn't have denoise. How could find it ?
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/52735731/66a88e22-9a20-47e3-9472-5ff8a9239e36)

**Comment by TinyTerra** [comment]
denoise has been added to pipeKSampler_v2 in (cfaecd01e7f3547b38c7e44f417655471a6b181a)
