### ISSUE TITLE
Suggestion: Put positive and negative strings in the PIPE

### ISSUE THREAD

**Issue by cjps-br** [TinyTerra/ComfyUI_tinyterraNodes#94]
the strings that generate positive and negative conditioning could also be part of the pipe and also be available as outputs in both pipeLoader and pipeKSampler

**Comment by TinyTerra** [comment]
This will be coming in v2, which should hopefully be out soon, I just need to do some polishing before releasing it

**Comment by TinyTerra** [comment]
pos_string and neg_string have been added to pipeKSampler_v2 and pipeKSamplerSDXL_v2 in (cfaecd01e7f3547b38c7e44f417655471a6b181a)

**Comment by cjps-br** [comment]
> pos_string and neg_string have been added to pipeKSampler_v2 and pipeKSamplerSDXL_v2 in ([cfaecd0](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/commit/cfaecd01e7f3547b38c7e44f417655471a6b181a))

I did some tests and verified that the "pos_string" output only receives the value of the positive field. If there is text being informed by the prepend_positive input, it is considered in the image conditioning, but its value is not placed in the "pos_string" output. the same observation applies to the negative fields.

Attached I include images that I used for testing (with the workflow embedded in them)

![base](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/75840971/120162f6-4705-42d9-9601-32c052200f30)
![base_with_positive](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/75840971/5dabc0e5-d8bb-4866-820f-2644abcb17fc)
![base_with_positive_as_input](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/75840971/5859357f-b9a6-477f-ae97-4b8937db1c99)

**Comment by TinyTerra** [comment]
Ah of course, sorry. That was an oversight
Should be fixed in 2b64695debe546e3c0e4b52bff13b620b0a87834
