### ISSUE TITLE
calc_cond_batch warning no longer a warning

### ISSUE THREAD

**Issue by GrigJr** [TinyTerra/ComfyUI_tinyterraNodes#96]
This used to be a warning until yesterday: 
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/126199406/862865e9-09a2-4a8b-9b42-c58bbc3a0a63)
Turned into an error today:
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/126199406/2c0851c6-3d8b-4bec-a403-b7a501c5a44b)

Anything I can do to fix it?

**Comment by TinyTerra** [comment]
Have you updated comfy, that function was refactored in base comfy on the 1st... so could be related to that.

Otherwise..  where is this occurring?
Do you have a sample prompt I can use to try and reproduce it?

**Comment by GrigJr** [comment]
I apologize, I forgot to mention: the issue does not reproduce on older installs. Only on the fresh install I did yesterday.

I got rid of it of the error, by removing https://github.com/Extraltodeus/ComfyUI-AutomaticCFG from the workflow. I guess it was causing the issue even if the ksampler was reporting it.
