### ISSUE TITLE
How can I completely uninstall a plugin?

### ISSUE THREAD

**Issue by xyq683812** [TinyTerra/ComfyUI_tinyterraNodes#99]
Hello, author. I have already removed the plugin from the custom_nodes folder, but the right-click menu still shows options like: reload node (ttN) / node dimensions (ttN). How can I completely remove these entries from the right-click menu?
![17b7b8addd430bde4eb55cc9b7c2a76](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/139227104/9c073184-c325-4c9f-b226-6dd6cd6671af)

**Comment by TinyTerra** [comment]
You will need to also remove the tinyterra folder in comfyui/web/extensions/

**Comment by xyq683812** [comment]
> You will need to also remove the tinyterra folder in comfyui/web/extensions/

Thanks, I solved the problem by deleting all related folders by searching keywords
